local _, ns = ...

ns.TemplateData = ns.TemplateData or {}
ns.TemplateData.TBC = {
	{
		name = "Karazhan",
		bosses = {
			{
				name = "Attumen the Huntsman",
				contents = table.concat({
					"|cyellow Attumen the Huntsman|",
					"{tank} Tank: ___",
					"{healer} Dispel |cred Intangible Presence| (curse)",
					"Face boss away from raid (Shadow Cleave)",
				}, "\n"),
			},
			{
				name = "Moroes",
				contents = table.concat({
					"|cyellow Moroes|",
					"{tank} MT - Moroes: ___",
					"{tank} OT (Gouge backup): ___",
					"",
					"|cred CC Assignments|",
					"{moon} Shackle: ___",
					"{square} Trap: ___",
					"{diamond} Shackle: ___",
					"{star} Trap/Turn Evil: ___",
					"",
					"|corange Kill Order|",
					"{skull} Healer add > {cross} Healer add > Others > Moroes",
				}, "\n"),
			},
			{
				name = "Maiden of Virtue",
				contents = table.concat({
					"|cyellow Maiden of Virtue|",
					"{tank} Tank: ___",
					"{healer} Dispel Holy Fire immediately",
					"All ranged/heals stay at max range",
					"Repentance stuns raid - HoTs before cast",
				}, "\n"),
			},
			{
				name = "Opera: Wizard of Oz",
				contents = table.concat({
					"|cyellow Opera - Wizard of Oz|",
					"{tank} MT - Roar: ___",
					"{skull} Dorothee > {cross} Roar > Strawman > Tinhead",
					"Then kill |cred The Crone|",
					"AoE fear from Roar - stay spread",
				}, "\n"),
			},
			{
				name = "Opera: Big Bad Wolf",
				contents = table.concat({
					"|cyellow Opera - Big Bad Wolf|",
					"{tank} Tank: ___",
					"|cred Little Red Riding Hood| = run away, raid peels",
					"Kite along walls, do not stop moving",
				}, "\n"),
			},
			{
				name = "Opera: Romulo and Julianne",
				contents = table.concat({
					"|cyellow Opera - Romulo & Julianne|",
					"{tank} Tank 1 - Romulo: ___",
					"{tank} Tank 2 - Julianne: ___",
					"|cred Both must die within 10 sec|",
					"P1: Julianne solo > P2: Romulo solo > P3: Both",
				}, "\n"),
			},
			{
				name = "The Curator",
				contents = table.concat({
					"|cyellow The Curator|",
					"{tank} Tank: ___",
					"{dps} Kill Astral Flares immediately (priority)",
					"|cgreen Evocation| = burn phase, all DPS on boss",
					"Flares = arcane damage, spread loosely",
				}, "\n"),
			},
			{
				name = "Shade of Aran",
				contents = table.concat({
					"|cyellow Shade of Aran|",
					"No tank - threat is random",
					"|cred DO NOT MOVE during Flame Wreath|",
					"Blizzard = move out",
					"Arcane Explosion = run to wall",
					"Interrupt Fireball and Frostbolt",
					"Elementals at 40% - AoE them down",
				}, "\n"),
			},
			{
				name = "Terestian Illhoof",
				contents = table.concat({
					"|cyellow Terestian Illhoof|",
					"{tank} MT - Illhoof: ___",
					"{tank} OT - Kil'rek (imp): ___",
					"|cred Demon Chains| = FREE SACRIFICED PLAYER (priority)",
					"{dps} Seed of Corruption from warlocks on imps",
				}, "\n"),
			},
			{
				name = "Netherspite",
				contents = table.concat({
					"|cyellow Netherspite|",
					"|cred Red Beam| (damage taken)",
					"{tank} Tank 1: ___ (5 stacks, swap)",
					"{tank} Tank 2: ___ (5 stacks, swap)",
					"",
					"|cgreen Green Beam| (healing)",
					"{healer} Soak: ___",
					"",
					"|cblue Blue Beam| (mana + spell damage)",
					"{dps} Soak 1: ___ (swap at 20 stacks)",
					"{dps} Soak 2: ___",
					"",
					"|cpurple Banish Phase| = run to back of room",
				}, "\n"),
			},
			{
				name = "Chess Event",
				contents = table.concat({
					"|cyellow Chess Event|",
					"Vehicle fight - control pieces on the board",
					"King: ___ (raid leader)",
					"Move pieces, use abilities, kill enemy King",
					"Cheat: Medivh buffs enemy pieces periodically",
				}, "\n"),
			},
			{
				name = "Prince Malchezaar",
				contents = table.concat({
					"|cyellow Prince Malchezaar|",
					"{tank} Tank: ___ (back to wall)",
					"Avoid {skull} Infernals (Hellfire AoE)",
					"P2: |cred Enfeeble| = affected players run out",
					"Ranged stay 30yd+ from boss",
					"Thrash = burst melee dmg, be ready to heal",
				}, "\n"),
			},
			{
				name = "Nightbane",
				contents = table.concat({
					"|cyellow Nightbane|",
					"{tank} MT: ___",
					"{tank} OT (fear backup): ___",
					"",
					"|corange Ground Phase|",
					"Tank swap on fear, face away from raid",
					"",
					"|cblue Air Phase|",
					"Stack on landing spot for Charred Earth",
					"Heal through Rain of Bones",
					"Kill Skeleton adds",
				}, "\n"),
			},
		},
	},
	{
		name = "Gruul's Lair",
		bosses = {
			{
				name = "High King Maulgar",
				contents = table.concat({
					"|cyellow High King Maulgar|",
					"{tank} MT - Maulgar: ___",
					"{tank} Blindeye the Seer: ___",
					"|cmage Mage Tank - Krosh (Spellsteal): ___",
					"|cwarlock Lock Tank - Olm (Subjugate): ___",
					"|cdruid Kiggler (immune to Poly): ___",
					"",
					"|corange Kill Order|",
					"{skull} Blindeye > {cross} Olm > {diamond} Krosh > {moon} Kiggler > {star} Maulgar",
				}, "\n"),
			},
			{
				name = "Gruul the Dragonkiller",
				contents = table.concat({
					"|cyellow Gruul the Dragonkiller|",
					"{tank} Tank: ___",
					"|cred Shatter| = SPREAD before Stoned debuff ends",
					"Growth = increasing damage (soft enrage)",
					"Hurtful Strike = 2nd on threat, stay in melee",
				}, "\n"),
			},
		},
	},
	{
		name = "Magtheridon's Lair",
		bosses = {
			{
				name = "Magtheridon",
				contents = table.concat({
					"|cyellow Magtheridon|",
					"{tank} MT - Magtheridon: ___",
					"",
					"|corange Channeler Tanks|",
					"{tank} Channeler 1: ___",
					"{tank} Channeler 2: ___",
					"{tank} Channeler 3: ___",
					"{tank} Channeler 4: ___",
					"{tank} Channeler 5: ___",
					"",
					"|cred Cube Clickers| (interrupt Blast Nova)",
					"{star} Cube 1: ___",
					"{diamond} Cube 2: ___",
					"{circle} Cube 3: ___",
					"{triangle} Cube 4: ___",
					"{moon} Cube 5: ___",
					"Click cubes at the same time on raid leader call",
				}, "\n"),
			},
		},
	},
	{
		name = "Serpentshrine Cavern",
		bosses = {
			{
				name = "Hydross the Unstable",
				contents = table.concat({
					"|cyellow Hydross the Unstable|",
					"|cblue Frost Resist Tank| (Water Form): ___",
					"|cgreen Nature Resist Tank| (Poison Form): ___",
					"",
					"Swap at |cred 4 stacks| of Mark debuff",
					"DO NOT cross center threshold accidentally",
					"Kill adds when they spawn at each transition",
				}, "\n"),
			},
			{
				name = "The Lurker Below",
				contents = table.concat({
					"|cyellow The Lurker Below|",
					"{tank} Tank: ___",
					"|cred Spout| = dive underwater or LOS behind pillar",
					"Inner ring: melee",
					"Outer ring: ranged + heals",
					"Kill adds from island platforms",
					"Whirl = melee run out",
				}, "\n"),
			},
			{
				name = "Leotheras the Blind",
				contents = table.concat({
					"|cyellow Leotheras the Blind|",
					"{tank} Warrior Tank (Human Form): ___",
					"|cwarlock Warlock Tank (Demon Form): ___",
					"",
					"|cred Inner Demon| = kill YOUR demon before",
					"  human form returns or you get MC'd",
					"At 15% both forms active simultaneously",
					"Whirlwind = melee run out",
				}, "\n"),
			},
			{
				name = "Fathom-Lord Karathress",
				contents = table.concat({
					"|cyellow Fathom-Lord Karathress|",
					"{tank} MT - Karathress: ___",
					"{tank} OT 1 - Sharkkis (Hunter): ___",
					"{tank} OT 2 - Tidalvess (Shaman): ___",
					"{tank} OT 3 - Caribdis (Priest): ___",
					"",
					"|corange Kill Order|",
					"{skull} Sharkkis > {cross} Tidalvess > {diamond} Caribdis > Karathress",
					"Each dead add empowers boss",
				}, "\n"),
			},
			{
				name = "Morogrim Tidewalker",
				contents = table.concat({
					"|cyellow Morogrim Tidewalker|",
					"{tank} MT - Morogrim: ___",
					"",
					"|cred Murloc AoE Groups|",
					"{tank} OT Left: ___",
					"{dps} AoE Left: ___",
					"{tank} OT Right: ___",
					"{dps} AoE Right: ___",
					"",
					"Watery Grave = 3 random ranged, heal them up",
					"Earthquake = stop casting",
				}, "\n"),
			},
			{
				name = "Lady Vashj",
				contents = table.concat({
					"|cyellow Lady Vashj|",
					"{tank} MT - Vashj: ___",
					"",
					"|cred Phase 2 - Tainted Core Relay|",
					"{star} Generator 1 chain: ___",
					"{diamond} Generator 2 chain: ___",
					"{circle} Generator 3 chain: ___",
					"{triangle} Generator 4 chain: ___",
					"Loot core > throw to next > deactivate generator",
					"",
					"|corange Add Tanks|",
					"{tank} Strider kiter: ___",
					"{tank} Naga tank: ___",
					"",
					"|cpurple Phase 3| = burn, avoid Toxic Spores",
				}, "\n"),
			},
		},
	},
	{
		name = "Tempest Keep: The Eye",
		bosses = {
			{
				name = "Al'ar",
				contents = table.concat({
					"|cyellow Al'ar|",
					"|corange Phase 1|",
					"{tank} Platform tanks (upper): ___  ___",
					"{tank} Add tank (lower): ___",
					"Boss flies between platforms, tank adds below",
					"",
					"|cred Phase 2|",
					"{tank} Tank 1: ___ (swap after Melt Armor)",
					"{tank} Tank 2: ___",
					"Kill Phoenix > destroy egg within 15 sec",
					"Meteor = spread, don't stack",
				}, "\n"),
			},
			{
				name = "Void Reaver",
				contents = table.concat({
					"|cyellow Void Reaver|",
					"{tank} Tank: ___",
					"Avoid |cred Arcane Orbs| (8yd splash)",
					"Pounding = AoE, heal through",
					"Simple fight - stay spread, avoid orbs",
				}, "\n"),
			},
			{
				name = "High Astromancer Solarian",
				contents = table.concat({
					"|cyellow High Astromancer Solarian|",
					"{tank} MT - Solarian: ___",
					"{tank} OT - Adds (every 50s): ___",
					"",
					"|cred Wrath of the Astromancer|",
					"Marked player runs AWAY from raid (explodes)",
					"AoE adds down quickly",
					"",
					"20% = Void Walker form, pure burn",
				}, "\n"),
			},
			{
				name = "Kael'thas Sunstrider",
				contents = table.concat({
					"|cyellow Kael'thas Sunstrider|",
					"|corange Phase 1 - Advisors (one at a time)|",
					"{tank} Thaladred (no aggro, kite): ranged kite",
					"{tank} Sanguinar: ___",
					"|cwarlock Capernian (lock tank): ___",
					"{tank} Telonicus: ___",
					"",
					"|cblue Phase 2 - Weapons|",
					"Kill weapons, LOOT THEM - used in later phases",
					"",
					"|cred Phase 3 - All Advisors|",
					"Tanks stand on advisor corpses before rez",
					"Same assignments as P1 but simultaneous",
					"",
					"|cpurple Phase 4 - Kael'thas|",
					"{tank} MT - Kael'thas: ___",
					"{tank} Phoenix kiter: ___",
					"|cred Shock Barrier > Pyroblast| = swap to boss, interrupt!",
					"Kill Phoenix > egg within 15 sec",
					"",
					"|cyellow Phase 5 - Gravity Lapse|",
					"Spread out, stay near ground, don't touch floor",
				}, "\n"),
			},
		},
	},
	{
		name = "Hyjal Summit",
		bosses = {
			{
				name = "Rage Winterchill",
				contents = table.concat({
					"|cyellow Rage Winterchill|",
					"{tank} Tank: ___",
					"8 waves of trash before boss",
					"Decurse |cblue Frost Armor| immediately",
					"Icebolt = frozen player, heal them when freed",
					"Death & Decay = move out of green circle",
				}, "\n"),
			},
			{
				name = "Anetheron",
				contents = table.concat({
					"|cyellow Anetheron|",
					"{tank} MT - Anetheron: ___",
					"{tank} OT - Infernals: ___",
					"Dispel |cpurple Sleep| (magic)",
					"Carrion Swarm = frontal cone, face away",
					"Vampiric Aura = boss heals from damage dealt",
					"Infernals = tank away, they despawn",
				}, "\n"),
			},
			{
				name = "Kaz'rogal",
				contents = table.concat({
					"|cyellow Kaz'rogal|",
					"{tank} Tank: ___",
					"|cred Mark of Kaz'rogal| = mana drain",
					"When your mana hits 0 you EXPLODE",
					"Mana users: run out when low mana",
					"Melee/hunters unaffected",
					"War Stomp = AoE stun, stay spread",
				}, "\n"),
			},
			{
				name = "Azgalor",
				contents = table.concat({
					"|cyellow Azgalor|",
					"{tank} MT: ___",
					"{tank} OT (Doomguard pickup): ___",
					"Rain of Fire = move out immediately",
					"Howl of Azgalor = AoE silence",
					"|cred Doom| = player dies after 20s, spawns Lesser",
					"  Doomguard - OT picks it up",
					"Cleave = face away from raid",
				}, "\n"),
			},
			{
				name = "Archimonde",
				contents = table.concat({
					"|cyellow Archimonde|",
					"{tank} Tank: ___",
					"",
					"|cred SURVIVAL FIGHT - if anyone dies,",
					"Soul Charge damages entire raid|",
					"",
					"|corange Group Setup| (Tremor Totem in every group)",
					"{shaman} G1: ___",
					"{shaman} G2: ___",
					"{shaman} G3: ___",
					"{shaman} G4: ___",
					"{shaman} G5: ___",
					"",
					"Tears of the Goddess = use when Air Burst",
					"Doomfire = run away from fire trail",
					"Finger of Death = stay in melee range",
					"Fear = Tremor/Berserker Rage",
				}, "\n"),
			},
		},
	},
	{
		name = "Black Temple",
		bosses = {
			{
				name = "High Warlord Naj'entus",
				contents = table.concat({
					"|cyellow High Warlord Naj'entus|",
					"{tank} Tank: ___",
					"Loot |cblue Tidal Shield Spine| > throw at boss shield",
					"|cred EVERYONE above 8500 HP before shield breaks|",
					"Shield break = 8500 AoE to entire raid",
					"Impaling Spine = dispel target, heal up",
				}, "\n"),
			},
			{
				name = "Supremus",
				contents = table.concat({
					"|cyellow Supremus|",
					"{tank} Tank: ___",
					"|corange Phase 1| = tank and spank",
					"|cred Phase 2| = fixates random player",
					"  Fixated player: KITE (boss moves fast)",
					"  Everyone else: avoid Volcanoes (blue fire)",
					"Hateful Strike = 2nd threat in melee",
				}, "\n"),
			},
			{
				name = "Shade of Akama",
				contents = table.concat({
					"|cyellow Shade of Akama|",
					"{tank} OT 1 - Channeler adds: ___",
					"{tank} OT 2 - Defender adds: ___",
					"Protect Akama as he walks to the Shade",
					"Kill Channelers to free Akama",
					"Once Akama reaches Shade = burn boss",
					"Sorcerer adds = interrupt Shadow Bolt",
				}, "\n"),
			},
			{
				name = "Teron Gorefiend",
				contents = table.concat({
					"|cyellow Teron Gorefiend|",
					"{tank} Tank: ___",
					"|cred Shadow of Death| = you die in 55s",
					"  As ghost: use abilities to kill Constructs",
					"  DO NOT let Constructs reach the raid",
					"Crushing Shadow = raid damage, stay spread",
					"Incinerate = random target, heal through",
				}, "\n"),
			},
			{
				name = "Gurtogg Bloodboil",
				contents = table.concat({
					"|cyellow Gurtogg Bloodboil|",
					"|corange Tank Rotation| (Acidic Wound stacks)",
					"{tank} Tank 1: ___",
					"{tank} Tank 2: ___",
					"{tank} Tank 3: ___",
					"",
					"|cred Bloodboil Soak Groups| (furthest 5 targets)",
					"Group A: ___",
					"Group B: ___",
					"Group C: ___",
					"Rotate groups - 3 stacks then swap",
					"",
					"|cpurple Fel Rage| = random player tanked, massive heals",
				}, "\n"),
			},
			{
				name = "Reliquary of Souls",
				contents = table.concat({
					"|cyellow Reliquary of Souls|",
					"|corange Phase 1 - Essence of Suffering|",
					"{tank} Feral Druid Tank: ___ (high dodge)",
					"NO HEALING works in this phase",
					"Spirit Shock = interrupt",
					"",
					"|cblue Phase 2 - Essence of Desire|",
					"{tank} Tank 1: ___ (swap at Deaden)",
					"{tank} Tank 2: ___",
					"Interrupt Spirit Shock (heals boss)",
					"",
					"|cred Phase 3 - Essence of Anger|",
					"{tank} Tank: ___",
					"Soul Scream = AoE, burn fast (soft enrage)",
				}, "\n"),
			},
			{
				name = "Mother Shahraz",
				contents = table.concat({
					"|cyellow Mother Shahraz|",
					"|cred Shadow Resist gear required (~300 SR)|",
					"",
					"|corange Saber Lash Tanks| (stack in front)",
					"{tank} Tank 1: ___",
					"{tank} Tank 2: ___",
					"{tank} Tank 3: ___",
					"",
					"|cpurple Fatal Attraction| = 3 players teleported",
					"  together - SPREAD APART immediately",
					"Beam attacks = random raid damage (SR mitigates)",
				}, "\n"),
			},
			{
				name = "The Illidari Council",
				contents = table.concat({
					"|cyellow Illidari Council|",
					"Shared HP - damage any, they all drop",
					"",
					"{tank} Gathios (Paladin) - MT: ___",
					"{healer} Interrupt |cred Malande| heals: ___  ___",
					"{tank} Malande (Priest) - OT: ___",
					"|crogue Veras (Rogue) - Kiter: ___",
					"|cmage Zerevor (Mage) - Spell Tank: ___",
					"",
					"Gathios + Veras can stack for cleave",
					"Malande has reflect shield - watch casts",
					"Zerevor casts Arcane Explosion - keep away",
				}, "\n"),
			},
			{
				name = "Illidan Stormrage",
				contents = table.concat({
					"|cyellow Illidan Stormrage|",
					"|corange Phase 1 & 5 - Normal|",
					"{tank} MT: ___",
					"Shear = reduce max HP, avoid with Shield Block/dodge",
					"",
					"|cblue Phase 2 - Flames of Azzinoth|",
					"{tank} Flame Tank L: ___",
					"{tank} Flame Tank R: ___",
					"Stay in fire aura range or raid takes damage",
					"",
					"|cred Phase 3 & 4 - Demon Form|",
					"|cwarlock Warlock Tank: ___",
					"Shadow Blast = fire resist aura",
					"Flame Burst = AoE, stay spread",
					"",
					"Phase 4: Maiev assists, trap Illidan in cage",
					"Parasitic Shadowfiend = run out if targeted",
				}, "\n"),
			},
		},
	},
	{
		name = "Zul'Aman",
		bosses = {
			{
				name = "Nalorakk",
				contents = table.concat({
					"|cyellow Nalorakk|",
					"{tank} Tank 1: ___",
					"{tank} Tank 2: ___",
					"",
					"|corange Troll Form| = both tanks in front",
					"  Brutal Swipe split between tanks",
					"|cred Bear Form| = tank swap (Mangle debuff)",
					"Surge = charges furthest target",
					"  Bait player: ___ (stand far)",
				}, "\n"),
			},
			{
				name = "Akil'zon",
				contents = table.concat({
					"|cyellow Akil'zon|",
					"{tank} Tank: ___",
					"|cred Electrical Storm| = player lifted in air",
					"  ENTIRE RAID stack under lifted player",
					"Static Disruption = nature damage, spread after",
					"Use Nature Resist totem/Aspect of the Wild",
				}, "\n"),
			},
			{
				name = "Jan'alai",
				contents = table.concat({
					"|cyellow Jan'alai|",
					"{tank} Tank: ___",
					"Kill LEFT Hatcher, let RIGHT hatch eggs",
					"AoE Dragonhawk adds as they spawn",
					"|cred Fire Bombs| = teleports raid, find safe spot",
					"At 35% all remaining eggs hatch - be ready",
				}, "\n"),
			},
			{
				name = "Halazzi",
				contents = table.concat({
					"|cyellow Halazzi|",
					"{tank} MT - Halazzi: ___",
					"{tank} OT - Spirit Lynx: ___",
					"Lynx splits at 75%, 50%, 25%",
					"|cred Kill Corrupted Lightning Totem ASAP|",
					"Transfigure = raid-wide damage, heal through",
				}, "\n"),
			},
			{
				name = "Hex Lord Malacrass",
				contents = table.concat({
					"|cyellow Hex Lord Malacrass|",
					"{tank} Tank: ___",
					"|corange Kill adds before boss reaches 80%|",
					"Soul Drain = boss gains 10% dmg per stack",
					"  Also reduces player dmg/healing by 1%",
					"|cred Spirit Bolts| = mass raid damage",
					"  Top everyone off before cast",
				}, "\n"),
			},
			{
				name = "Zul'jin",
				contents = table.concat({
					"|cyellow Zul'jin|",
					"{tank} Tank: ___",
					"",
					"|corange 5 Phases (animal forms)|",
					"P1 Troll: tank and spank, Whirlwind dodge",
					"P2 Bear: Creeping Paralysis, dispel/heal",
					"P3 Eagle: NO threat table, dodge tornadoes",
					"P4 Lynx: Claw Rage on random, big heals needed",
					"P5 Dragonhawk: avoid fire columns, BURN",
				}, "\n"),
			},
		},
	},
	{
		name = "Sunwell Plateau",
		bosses = {
			{
				name = "Kalecgos",
				contents = table.concat({
					"|cyellow Kalecgos|",
					"|corange Normal Realm|",
					"{tank} Tank - Kalecgos: ___",
					"",
					"|cpurple Spectral Realm|",
					"{tank} Tank - Sathrovarr: ___",
					"",
					"|cred Portal Rotation| (every 20-25s)",
					"Always have {tank} + {healer} + {dps} in both realms",
					"Kicked out after 60s, can't re-enter for 60s",
					"Assign portal order for tanks/healers",
				}, "\n"),
			},
			{
				name = "Brutallus",
				contents = table.concat({
					"|cyellow Brutallus|",
					"|corange Tank Swap| (every 3 Meteor Slashes)",
					"{tank} Tank 1: ___",
					"{tank} Tank 2: ___",
					"",
					"|cred Meteor Slash| = stack in cone to split damage",
					"|cpurple Burn| debuff = move AWAY (spreads to nearby)",
					"6 min hard enrage - DPS CHECK",
				}, "\n"),
			},
			{
				name = "Felmyst",
				contents = table.concat({
					"|cyellow Felmyst|",
					"|corange Tank Swap| (on Corrosion = 2x damage)",
					"{tank} Tank 1: ___",
					"{tank} Tank 2: ___",
					"",
					"|cblue Air Phase|",
					"Avoid Demonic Vapor (green gas)",
					"|cred Fog of Corruption| = dodge the beam (MC's you)",
					"Run to sides",
					"",
					"|corange Ground Phase|",
					"Encapsulate = heal targeted player",
					"Gas Nova = AoE, heal through",
				}, "\n"),
			},
			{
				name = "Eredar Twins",
				contents = table.concat({
					"|cyellow Eredar Twins|",
					"{tank} Sacrolash (Shadow) - Melee Tank: ___",
					"|cwarlock Alythess (Fire) - Warlock Tank: ___",
					"",
					"|cblue Shadow Resist| team near Sacrolash",
					"|cred Fire Resist| team near Alythess",
					"",
					"Conflagration = run OUT of raid",
					"Shadow Nova = AoE near Sacrolash",
					"Flame Sear = spread fire damage",
				}, "\n"),
			},
			{
				name = "M'uru",
				contents = table.concat({
					"|cyellow M'uru / Entropius|",
					"{tank} MT - M'uru: ___",
					"",
					"|corange Add Waves| (every 60s from each side)",
					"{tank} OT Left - Berserkers: ___",
					"{tank} OT Right - Berserkers: ___",
					"Kill: 2 Berserkers + 1 Mage each wave",
					"{tank} Void Sentinel tank: ___ (away from raid)",
					"",
					"|cred Phase 2 - Entropius| (at 0%)",
					"Stack for Negative Energy (split damage)",
					"Spread for Darkness",
					"Burn fast",
				}, "\n"),
			},
			{
				name = "Kil'jaeden",
				contents = table.concat({
					"|cyellow Kil'jaeden|",
					"{tank} Tank: ___",
					"",
					"|cred Dragon Orb Clickers| (4 corners)",
					"{star} Orb 1: ___",
					"{diamond} Orb 2: ___",
					"{circle} Orb 3: ___",
					"{triangle} Orb 4: ___",
					"",
					"|cpurple Shield of the Blue| = REQUIRED for Darkness",
					"  Orb clicker activates shield on RL call",
					"Fire Bloom = 5 random, spread out",
					"Legion Lightning = move away (chains)",
					"Armageddon = avoid meteor impacts",
				}, "\n"),
			},
		},
	},
}
